apiVersion: v2
name: auth1
description: A Helm chart for Kubernetes
type: application
version: 0.1.23
appVersion: "0.2.8"
dependencies:
  - name: redis
    version: 15.x.x
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
maintainers:
  - name: akeamc
    email: ake@amcoff.net
